-- Create the leads table if it doesn't exist
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  mobile text,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.leads enable row level security;

-- Create policy to allow anyone (anon) to insert leads
create policy "Allow public inserts"
  on public.leads
  for insert
  to anon
  with check (true);

-- Create policy to allow admins (authenticated) to view leads
create policy "Allow authenticated view"
  on public.leads
  for select
  to authenticated
  using (true);
